#!/bin/sh
 
# shove's little brother.
# Basically does the opposite; 'unstows' the file.

DOTFILES=$HOME/.dotfiles

[ -z "$1" ] && echo "Usage: $0 FILE..." && exit

for arg; do
	# Check if even is a symlink
	[ ! -h "$arg" ] && echo "$1 is not a symbolic link. Aborting." && exit 1

	# Check if the symlink points to our dotfiles dir somewhere
	SYM_PATH="$(readlink -f "$arg")"
	[ "${SYM_PATH##$DOTFILES/}" = "$SYM_PATH" ] && echo "$arg does not point to a path within your dotfiles? Aborting." && exit 1

	# Remove the symlink
	echo "Removing $arg."
	rm "$arg"

	echo "Moving linked file of $arg out of dotfiles"
	mv "$SYM_PATH" "$arg"
done

echo "Done."
