#!/bin/sh

wall="$HOME/.config/wall.jpg"

if [ -f "$1" ]; then
	cp -f "$1" "$wall"
	[ -d $HOME/.cache/wal ] && rm -r $HOME/.cache/wal
fi

swaymsg 'output "*" bg '"$wall"' fill'

command -v wal >/dev/null && [ ! -z $NT_USE_WAL ] && wal -n -t -i "$wall" --cols16 darken -o $HOME/.config/wal/postrun
