#!/bin/sh

mimetype="$(file --dereference --brief --mime-type "$1")"
case "$mimetype" in
	*/pdf) pdftotext -q -l 10 "$1" - ;;
	text/html) w3m -dump "$1" ;;
	text/*) highlight --out-format=xterm256 --replace-tabs=4 --force "$1" || cat "$1" ;;
	image/*) identify -verbose "$1" ;;
	audio/*) eyeD3 -l critical "$1" ;;
	*) stat -L "$1" && echo "" && file --dereference --brief "$1" ;;
esac

