#!/bin/sh

[ ! -d "$HOME/.local/narb/stows" ] && echo "Stow metadata does not exist. Cannot upgrade." && exit 1

echo ""
echo "Nick's dotfiles: upgrade"
echo "  - Fetching git repo..."
cd $HOME/.dotfiles
git fetch || { echo "Failed to fetch." && exit 1; }

echo ""
echo "  - Detecting stows..."
stows=""
cd $HOME/.local/narb/stows
for s in *; do stows="$stows $s"; done
cd $HOME/.dotfiles
echo '' > /tmp/narb-upgrade
for s in *; do [ -d "$s" ] && echo "$s" > /tmp/narb-upgrade; done


echo ""
echo "  - Unstowing existing modules..."
eval "stow --verbose=0 -D $stows"
echo "All existing stows were unstowed."

echo ""
echo "  - Upgrading git repo..."
git pull --rebase

echo ""
echo "  - Stowing back modules that still exist..."
for s in $stows; do
	[ ! -d "$s" ] && echo "Module '$s' no longer exists" && continue
	echo "Stowing module '$s'"
	stow --verbose=0 -S "$s"
done

echo ""
echo "  - Checking for fresh new modules..."
for s in *; do
	[ ! -d "$s" ] && continue
	grep -xq "$s" /tmp/narb-upgrade && continue
	echo -n "Module '$s' is new. Stow it? [yn] "
	read myn
	[ "$myn" = "y" ] && echo "Stowing module '$s'" && stow --verbose=0 -S "$s"
done

echo ""
echo "dotfiles upgrade should be complete!"
