#!/bin/sh

# This script was made by `goferito` on Github.
# Some cleanup by Luke Smith
# Modified for sway by ntay

[ -z "$1" ] && echo "No direction provided" && exit 1
distanceStr="2 px or 2 ppt"

[ -z "$WAYLAND_DISPLAY" ] && prog="i3-msg" || prog="swaymsg"

moveChoice() {
  $prog resize "$1" "$2" "$distanceStr" | grep '"success":true' || \
    $prog resize "$3" "$4" "$distanceStr"
}

case $1 in
  up)
    moveChoice grow up shrink down
    ;;
  down)
    moveChoice shrink up grow down
    ;;
  left)
    moveChoice shrink right grow left
    ;;
  right)
    moveChoice grow right shrink left
    ;;
esac
