#!/bin/sh

setwp		# Fix background if screen size/arrangement has changed.
remapkb		# Re-remap keys if keyboard added (for laptop bases)
pgrep -x dunst >/dev/null && killall dunst && setsid dunst & # Restart dunst to ensure proper location on screen
pgrep -x keynav >/dev/null && killall keynav && setsid keynav & # Restart keynav to ensure correct overlay size
pgrep -x polybar >/dev/null && $HOME/.config/polybar/launch.sh & # Restart polybar
pgrep -x i3 >/dev/null && type i3-ws &>/dev/null && i3-ws --init >/dev/null # i3-ws reinit if using i3
