#!/bin/sh

termargs=

# Different terminals have different ways to spawn with classnames, so...
if [ "$1" = "-float" ]; then
	shift
	case "$TERMINAL" in
		urxvt*) termargs=$(echo -name floater) ;;
		alacritty) termargs='-class=floater' ;;
		foot) termargs='--app-id=foot-floater' ;;
		kitty) termargs=$(echo --app-id kitty-floater) ;;
		*) termargs=$(echo -n floater -g 120x34) ;;
	esac
fi

# Interactive shell to ensure settings loaded, in case
[ ! -z "$1" ] && set -- -e $SHELL -i -c "$*"

exec $TERMINAL $termargs "$@"
