#!/bin/sh

[ "$BLOCK_BUTTON" = "1" ] && nnotify batw
[ "$BLOCK_BUTTON" = "3" ] && termfloat sudo powertop

batc="$(cat /sys/class/power_supply/BAT0/capacity)"
[ "$batc" -gt 97 ] && batc="full"
[ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ] && batc="${batc}+"

echo "$batc"
