#!/bin/sh

# corona download update stats for bar...

# click action
case "$1" in
	show) curl -s "https://corona-stats.online" | less -r && exit ;;
	showau) curl -s "https://corona-stats.online/AU?source=1" | less -r && exit ;;
	*)
		case "$BLOCK_BUTTON" in
			1) termfloat $0 show ;;
			3) $BROWSER "https://www.coronavirus.vic.gov.au/victorian-coronavirus-covid-19-data" && exit ;;
		esac
		;;
esac

statsfile="$HOME/.cache/corona-stats"

# helper grabber html random elements lol...
grab() { grep -o '[0-9,][0-9,]*.\{65\}'"$1" /tmp/corona-stats-raw | cut -f1 -d'<' | tr -d ',' ;}

# if file too old or doesnt exist (6hr)
dl() {
	# get and parse...
	curl -s "https://www.coronavirus.vic.gov.au/victorian-coronavirus-covid-19-data" | grep -A2 'rpl-main-content' > /tmp/corona-stats-raw \
		&& echo "$(grab '>total cases')(+$(grab 'cases acquired locally')),$(grab 'total lives lost')(+$(grab 'lives lost (last 24'))" > "$statsfile"
}
{ [ ! -s "$statsfile" ] || test $(find "$statsfile" -mmin +360 2>/dev/null) ;} && { dl || { echo "fail :("; rm "$statsfile" ; exit 1 ;} ;}

cat "$statsfile"
