#!/bin/sh

[ "$BLOCK_BUTTON" = "1" ] && nnotify wlan
[ "$BLOCK_BUTTON" = "3" ] && nnotify eth

# wifi: use rssi_to_perc from slstatus
[ "$(cat /sys/class/net/wlp*/operstate 2>/dev/null)" = "up" ] && \
	wperc="w$(awk '/^\s*w/ { print $4 >= -50 ? 100 : ($4 <= -100 ? 0 : (2 * ($4 + 100))) }' /proc/net/wireless)"

# eth: just if link is up
[ "$(cat /sys/class/net/enp*/operstate 2>/dev/null)" = "up" ] && \
	estatus="e"

[ -z $wperc ] && [ -z $estatus ] && echo "down" && exit 1

# vpn (wireguard): check if interface exists (as no real 'up' state with udp)
[ ! -z "$(cat /sys/class/net/wg*/operstate 2>/dev/null)" ] && \
	vpnstatus="v"

echo "$wperc$estatus$vpnstatus"
