#!/bin/sh

case $BLOCK_BUTTON in
	1) $TERMINAL -name floater -e sudo powertop ;;
esac

percent=$(cat /sys/class/power_supply/"$BATTERY"/capacity) || exit
status=$(cat /sys/class/power_supply/"$BATTERY"/status)

#[ "$status" != "Charging" ] && [ "$percent" -lt 20 ] && notify-send -u critical "Battery" "Low battery!"

#icon="🔌"
#[ "$status" != "Charging" ] && icon="🔋"

icon=""
if [ "$status" != "Discharging" ]; then
	[ "$percent" -gt "97" ] && echo "full" && exit
	icon = "++"
fi

echo $percent%$icon
