#!/bin/sh

case $BLOCK_BUTTON in
	1) $TERMINAL -e nmtui ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && echo "🖧  (D/C)" && exit

strength=$(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) "%" }')
name=$(nmcli -t -f NAME connection show --active)

echo "🖧  $name ($strength)"
