[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = " $icon $percentage "
[[block.click]]
button = "left"
cmd = "nnotify disk /"

[[block]]
block = "net"
#format = " $icon {$signal_strength $ssid $frequency|Wired}"
format = " $icon {$signal_strength $ip $frequency|Wired} "
[[block.click]]
button = "left"
cmd = "termlaunch -float nmtui"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
[[block.click]]
button = "left"
cmd = "termlaunch -float sudo powertop"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%x(%a) %H:%M', l:zh_CN) "
[[block.click]]
button = "left"
cmd = "nnotify time"
[[block.click]]
button = "right"
cmd = "nnotify cal"
