#!/bin/sh
# Generate nex banners...

[ $(id -u) -ne 0 ] && echo "Run as root." && exit 1

# may need to change this
mainuser="nick"

bannerfile="/home/$mainuser/.local/nex/banner/$(hostname)"
[ ! -f "$bannerfile" ] && echo "No banner exists; create one at $bannerfile" && exit 1
banner="$(cat "$bannerfile")"

# System Welcome (issue)
printf '[System Welcome]\n%s\n' "$banner" > /etc/issue

# LUKS message
printf "$(cat /home/$mainuser/.local/nex/arch/nickmsg-initcpio.hook)" "$banner" > /etc/initcpio/hooks/nickmsg

echo 'Done!'
echo 'Be sure to have the nickmsg hook in mkinitcpio if not already there, and also to regenerate the kernel!'
