#!/bin/sh

ip="(unknown)"
if [ "$1" = "pub" ]; then
	_ip="$(curllog https://ipinfo.io/ip)" && ip="$_ip"
	#_ip="$(dig +short myip.opendns.com @resolver1.opendns.com -4)" && ip="$_ip"
else
	if [ ! -z "$NT_IS_MACOS" ]; then
		# using ifconfig instead of ipconfig because could be a tunnel (VPN)...
		iface="$(route -n get default | sed -n 's/.*interface: \(.*\)/\1/p')" && \
		echo "[DEBUG] interface: $iface" && \
		_ip="$(ifconfig "$iface" | sed -n 's/.*inet \([0-9\.]*\) .*/\1/p')" && ip="$_ip"
	else
		_ip="$(ip -j route show default | jq -r 'first | .prefsrc')" && ip="$_ip"
	fi
fi

echo "$ip"
