#!/bin/sh

ip="(unknown)"
if [ "$1" = "pub" ]; then
	_ip="$(dig +short myip.opendns.com @resolver1.opendns.com -4)" && ip="$_ip"
else
	_ip="$(ip -j route show default | jq -r 'first | .prefsrc')" && ip="$_ip"
fi

echo "$ip"
