#!/bin/sh

confs="\
r	ranger	$HOME/.config/ranger/rc.conf
v	neovim	$HOME/.config/nvim/init.vim
b	bash	$HOME/.bashrc
z	zsh	$HOME/.config/zsh/.zshrc
xr	xresources	$HOME/.Xresources
x	xinitrc	$HOME/.xinitrc
p	profile	$HOME/.profile
o	i3status-rust	$HOME/.config/i3status-rust/config.toml
c	picom	$HOME/.config/picom.conf
a	aliasrc	$HOME/.config/aliasrc
i	i3	$HOME/.config/i3/config
s	sway	$HOME/.config/sway/config
I	inputrc	$HOME/.config/inputrc
l	lf	$HOME/.config/lf/lfrc
f	fontconfig	$HOME/.config/fontconfig/fonts.conf
d	dunst	$HOME/.config/dunst/dunstrc
t	tmux	$HOME/.tmux.conf
A	aliasrc-override	$NEX_OVERRIDES/aliasrc.$NEX_HOST
P	profile-override	$NEX_OVERRIDES/profile.$NEX_HOST
X	xprofile-override	$NEX_OVERRIDES/xprofile.$NEX_HOST
J	jumptool	$HOME/.scripts/tools/jumptool
Jc	confs-override	$NEX_OVERRIDES/confs.$NEX_HOST
Jd	dirs-override	$NEX_OVERRIDES/dirs.$NEX_HOST"

dirs="\
c	cloud	$HOME/cloud
d	dev	$HOME/dev
D	downloads	$HOME/downloads
u	uni	$HOME/uni
C	config	$HOME/.config
S	scripts	$HOME/.scripts
St	tools	$HOME/.scripts/tools
Sb	bar	$HOME/.scripts/bar
Sp	personal	$HOME/.scripts/personal
t	template	$HOME/template
N	nex	$HOME/.local/nex
H	overrides	$NEX_OVERRIDES"

[ -f "$NEX_OVERRIDES/confs.$NEX_HOST" ] && confs="$confs\n$(cat $NEX_OVERRIDES/confs.$NEX_HOST)"
[ -f "$NEX_OVERRIDES/dirs.$NEX_HOST" ] && dirs="$dirs\n$(cat $NEX_OVERRIDES/dirs.$NEX_HOST)"

sel="$2"
selector() {
	if [ "$sel" = "fzf" ]; then
		choice="$(echo "$1" | cut -d'	' -f 2 | fzf --prompt="$2: ")" || exit 1
	else
		choice="$(echo "$1" | cut -d'	' -f 2 | dmenu -i -p "$2")" || exit 1
	fi
	echo "$1" | awk -F'	' '$2 == "'"$choice"'" { print $3; exit; }'
}

case "$1" in
	generate)
		# term generate alias
		: > $HOME/.config/shortcutrc
		echo "$confs" | awk -F'	' '{ print "alias cf" $1 "=\"" "$EDITOR " $3 "\"" }' >> $HOME/.config/shortcutrc
		echo "$dirs" | awk -F'	' '{ print "alias cd" $1 "=\"" "cd " $3 "\"" }' >> $HOME/.config/shortcutrc
		# ranger jumps
		: > $HOME/.config/ranger/shortcut.conf
		echo "$confs" | awk -F'	' '{ print "map C" $1 " cd " $3 }' >> $HOME/.config/ranger/shortcut.conf
		echo "$dirs" | awk -F'	' '{ print "map g" $1 " cd " $3 }' >> $HOME/.config/ranger/shortcut.conf
		# zsh named dirs
		echo "$dirs" | awk -F'	' '{ print "hash -d " $2 "=" $3 }' > $HOME/.config/zshnameddirs
		;;
	config)
		# pick config
		conf="$(selector "$confs" "edit config?")"
		{ [ "$sel" = "fzf" ] && $EDITOR "$conf" || setsid $TERMINAL -e $EDITOR "$conf" ;}
		;;
	dir)
		# pick dir
		dir="$(selector "$dirs" "jump to?")"
		[ -d "$dir" ] && cd "$dir" && \
			{ [ "$sel" = "fzf" ] && echo "$dir" || setsid $TERMINAL ;}
		;;
	*)
		exit 1
		;;
esac
