#!/bin/bash

tz_format="+%Y-%m-%d %a %H:%M"
tzs=("Asia/Seoul" 
     "Asia/Hong_Kong"
     "America/Los_Angeles"
     )

dt="Local: $(date "$tz_format")"
for tz in "${tzs[@]}"
do
	dt="$dt\n$tz: $(TZ=":$tz" date "$tz_format")"
done
notify-send "🕒 Date/Times" "$dt"
