#!/bin/sh

# Repeat rate
xset r rate 200 50

# Caps is Escape
# Menu is SuperR
setxkbmap -option caps:escape -option altwin:menu_win


# Laptop-specific

# Disable touchpad
touchpadtoggle off silent

# Trackpoint sens settings
[ ! -z "$TRACKPOINT_NAME" ] \
	&& xinput --set-prop "$TRACKPOINT_NAME" "libinput Accel Speed" 0.65 \
	&& xinput --set-prop "$TRACKPOINT_NAME" "libinput Accel Profile Enabled" 0 1
