#!/bin/sh

sstype="$1" 
[ -z "$sstype" ] && sstype="$(printf "rect\\nwindow\\nscreen" | dmenu -l 6 -i -p "screenshot type?")"

case $sstype in
	"rect")
		ssargs="-s"
		sswin="$(ps -p $(xdotool getactivewindow getwindowpid) -o comm=)"
		;;
	"window")
		ssargs="-i $(xdotool getactivewindow)"
		sswin="$(ps -p $(xdotool getactivewindow getwindowpid) -o comm=)"
		;;
	"screen")
		sswin="screen"
		;;
	*) exit ;;
esac

# cleanse window name
sswin="$(echo "$sswin" | sed -e 's/[^A-Za-z0-9._-]/_/g')"

if [ "$2" = "nosave" ]; then
	maim --delay=0.35 --hidecursor $ssargs | xclip -selection clipboard -t image/png && notify-send "Screenshot ($sstype)" "Screenshot copied to clipboard."
else
	p="$HOME/Screenshots/"
	f="$(date '+%y%m%d-%H%M%S')-$sswin-$sstype.png"
	pf="$p$f"
	maim --delay=0.35 --hidecursor $ssargs "$pf" && xclip -selection clipboard -t image/png -i "$pf" && notify-send "Screenshot ($sstype)" "Screenshot $f copied to clipboard, and saved to folder."
fi
