#!/bin/sh

pgrep -x dmenu && exit

case "$(printf "shutdown\\nreboot\\nsuspend\\nrefresh\\nlogout" | dmenu -i -p "time to leave?")" in
	"shutdown") shutdown now ;;
	"reboot") reboot ;;
	"suspend") systemctl suspend ;;
	"refresh") kill -HUP $(pidof -s dwm) ;;
	"logout") kill -TERM $(pidof -s dwm) ;;
esac
