#!/bin/sh

pgrep -x dmenu && exit

if pgrep -x dwm; then
	refreshwm="kill -HUP $(pidof -s dwm)" 
	exitwm="kill -TERM $(pidof -s dwm)"
elif pgrep -x bspwm; then
	refreshwm="bspc wm -r"
	exitwm="bspc quit"
elif pgrep -x i3; then
	refreshwm="i3-msg reload"
	exitwm="i3-msg exit"
fi

case "$(printf "shutdown\\nreboot\\nsuspend\\nrefresh\\nlogout" | dmenu -i -p "time to leave?")" in
	"shutdown") shutdown now ;;
	"reboot") reboot ;;
	"suspend") systemctl suspend ;;
	"refresh") `echo $refreshwm` ;;
	"logout") `echo $exitwm` ;;
esac
