#!/bin/sh

pgrep -x dmenu && exit

if pgrep -x dwm; then
	refreshwm="kill -HUP $(pidof -s dwm)" 
	exitwm="kill -TERM $(pidof -s dwm)"
elif pgrep -x bspwm; then
	refreshwm="bspc wm -r"
	exitwm="bspc quit"
elif pgrep -x i3; then
	refreshwm="i3-msg reload"
	exitwm="i3-msg exit"
fi

if [ -d /usr/lib/systemd ]; then
	suspendcmd="systemctl suspend-then-hibernate"
	extraoptions="$extraoptions\nsuspend"

	hibcmd="systemctl hibernate"
	grep "resume=" /proc/cmdline >/dev/null 2>&1 \
		&& extraoptions="$extraoptions\nhibernate"
fi

case "$(printf "shutdown\\nreboot$extraoptions\\nrefresh\\nlogout" | dmenu -i -p "time to leave?")" in
	"shutdown") shutdown now ;;
	"reboot") reboot ;;
	"suspend") `echo $suspendcmd` ;;
	"hibernate") `echo $hibcmd` ;;
	"refresh") `echo $refreshwm` ;;
	"logout") `echo $exitwm` ;;
esac
