#!/bin/sh

wall="$HOME/.config/wall.jpg"

[ -f "$1" ] && cp -f "$1" "$wall" && xwallpaper --zoom "$wall" && rm $HOME/.cache/wal/schemes/*__config_wall_jpg*.json

xwallpaper --zoom "$wall"
wal -n -t -b "#060204" -i "$wall" -o $HOME/.config/wal/postrun
