#!/bin/sh

wall="$HOME/.config/wall.jpg"

if [ -f "$1" ]; then
	cp -f "$1" "$wall"
	[ -d $HOME/.cache/wal ] && rm $HOME/.cache/wal/schemes/*__config_wall_jpg*.json
fi

swaymsg 'output "*" bg '"$wall"' fill'

command -v wal >/dev/null && [ ! -z $NT_USE_WAL ] && wal -n -t -i "$wall" --cols16 darken
