#!/bin/bash

clear

c00=$'\e[0;30m'
c01=$'\e[0;31m'
c02=$'\e[0;32m'
c03=$'\e[0;33m'
c04=$'\e[0;34m'
c05=$'\e[0;35m'
c06=$'\e[0;36m'
c07=$'\e[0;37m'

c08=$'\e[1;90m'
c09=$'\e[1;91m'
c10=$'\e[1;92m'
c11=$'\e[1;93m'
c12=$'\e[1;94m'
c13=$'\e[1;95m'
c14=$'\e[1;96m'
c15=$'\e[1;97m'

f0=$'\e[1;90m'
f1=$'\e[1;37m'
f2=$'\e[0;37m'

kernel=$(uname -rmo)
cpuspe=$(grep 'model name' /proc/cpuinfo| sed 1q|sed 's/^.*:\ *//')

system=$(cat /etc/os-release | sed '2,$d;s/NAME="//;s/"//')

if [ -n "$DISPLAY" ]; then
    wmname=$(wmctrl -m | grep -i name | awk '{print $2}')
    #termfn=$(xrdb -query | awk '/URxvt.font/ {print $2}' | sed 's/xft://;s/:pixelsize//;s/=/\ /')
    termfn=$(fc-match monospace | sed 's/.*: "\([^"]*\).*"/\1/')
    systfn=$(sed -n 's/^[gtk].*font.*"\(.*\)".*$/\1/p' ~/.config/gtk-2.0/gtkrc-2.0)
else
    wmname="none"
    termfn="none"
    systfn="none"
fi

pkgnum=$(rpm -qa | wc -l) || pkgnum=$(pacman -Q|wc -l)
birthd="$(rpm -q basesystem --qf '%{installtime:date}\n')" || birthd=$(sed -n '1s/^\[\([0-9-]*\).*$/\1/p' /var/log/pacman.log | tr - .)
memuse=$(free -m | awk 'FNR==2 { print $3 " MiB / " $2 " MiB" }')


cat << EOF
${f0}${c15}  ╔════╗	
${c08}  ║██  ║ ${c10}OS ${f0}........... $c06$system
${c08}  ║  ██║ ${c10}name ${f0}......... $c06$HOSTNAME
${c01}  ║██  ║ ${c10}birthday${f0}...... $c06$birthd
${c09}  ║  ██║ ${c10}packages ${f0}..... $c06$pkgnum
${c02}  ║██  ║
${c10}  ║  ██║ ${c10}wm ${f0}........... $c06$wmname
${c03}  ║██  ║ ${c10}shell ${f0}........ $c06$SHELL
${c11}  ║  ██║ ${c10}terminal ${f0}..... $c06$TERM
${c04}  ║██  ║ ${c10}term font ${f0}.... $c06$termfn
${c12}  ║  ██║ ${c10}system font ${f0}.. $c06$systfn
${c05}  ║██  ║
${c13}  ║  ██║ ${c10}kernel ${f0}....... $c06$kernel
${c06}  ║██  ║ ${c10}processor ${f0}.... $c06$cpuspe
${c14}  ║  ██║ ${c10}memory ${f0}....... $c06$memuse
${c07}  ╚════╝
EOF

tput civis
read a
tput cnorm
