#!/bin/sh

# Open a terminal window in the same directory as the currently active window.
# From lukesmithxyz, modified to work on alacritty

PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)

# Get child PID as required
# Alacritty needs first child, then others use the last(?)
[ "$TERMINAL" = "alacritty" ] \
	&& CHILD_PID="$(pgrep -P "$PID")" \
	|| CHILD_PID="$(pstree -lpA "$PID" | tail -n 1 | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')"

cd "$(readlink /proc/"$CHILD_PID"/cwd)" || return 1
"$TERMINAL"
