#!/bin/sh

# Different terminals have different ways to spawn with classnames, so...
case "$TERMINAL" in
	urxvt*)
		$TERMINAL -name floater -e $@ ;;
	alacritty)
		$TERMINAL --class=floater -e $@ ;;
	*)
		$TERMINAL -n floater -g 120x34 -e $@ ;;
esac
