#!/bin/sh

# Open a terminal window in the same directory as the currently active window.
# From lukesmithxyz
#   X: modified to work on alacritty
#   WL: modified to work with foot+sway

if [ "$DESKTOP_SESSION" = "sway" ]; then
	PID=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?, .floating_nodes[]?) | select(.focused) | .pid')
else
	PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
fi

# Get child PID as required
if [ "$TERMINAL" = "alacritty" ] || [ "$TERMINAL" = "foot" ]; then
	# Alacritty/foot needs first child, then others use the last(?)
	CHILD_PID="$(pstree -lpA "$PID" | head -n 1 | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')"
else
	CHILD_PID="$(pstree -lpA "$PID" | tail -n 1 | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')"
fi

cd "$(readlink /proc/"$CHILD_PID"/cwd)" || exit 1
"$TERMINAL"
