#!/bin/sh

termargs=

# Different terminals have different ways to spawn with classnames, so...
if [ "$1" = "-float" ]; then
	shift
	case "$TERMINAL" in
		urxvt*) termargs=$(echo -name floater) ;;
		alacritty) termargs='-class=floater' ;;
		foot) termargs='--app-id=foot-floater' ;;
		*) termargs=$(echo -n floater -g 120x34) ;;
	esac
fi

# ... then we launch in login shell to ensure settings are all loaded too
exec $TERMINAL $termargs -e $SHELL -i -c "$*"
