#!/bin/sh

# timestamps with any decimal points/guessed precision (ns/ms/etc)
# also just the current time with no arg.

d=date
command -v gdate >/dev/null && d=gdate

if [ -z "$1" ]; then
	$d +%s%N | sed 's/./&./10'
else
	$d -d "@$(echo "$1" | sed '/^[0-9]\{10\}\([0-9]\{3\}\)\{1,3\}$/ s/./&./10')"
fi
