#!/bin/sh

[ -z "$TOUCHPAD_NAME" ] && exit

if [ "$1" = "off" ] || xinput list-props "$TOUCHPAD_NAME" | grep -q "Device Enabled.*1$"; then
	xinput disable "$TOUCHPAD_NAME"
	[ "$2" != "silent" ] && notify-send "touchpadtoggle" "Disabled $TOUCHPAD_NAME."
else
	xinput enable "$TOUCHPAD_NAME"
	[ "$2" != "silent" ] && notify-send "touchpadtoggle" "Enabled $TOUCHPAD_NAME."
fi
