#!/bin/sh

pgrep -x dmenu && exit

# device selection
devices="$(sudo -A usbguard list-devices -b \
	| grep "hotplug" | sed 's/^\([0-9]*\):.* name "\([^"]*\)".*/\1: \2/')"
[ "$devices" = "" ] && notify-send "usbguardmenu" "No blocked hotplug usbguard devices found." && exit 0

device="$(echo "$devices" \
	| dmenu -i -p "device to unblock?" \
	| awk -F':' '{print $1}')"
[ "$device" = "" ] && exit 1

sudo -A usbguard allow-device "$device" \
	&& notify-send "usbguardmenu" "Temporarily allowed USB device #$device." && exit 0
