#!/bin/sh

#
# nick's shell aliases
#


# General shell
alias q="exit"

# General utility
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias ll="ls -lah"
alias lsd="ls -d"
alias sudo="sudo "
alias ag="rg -S"
alias tree="tree -C"
# could use `kitten ssh`, but don't want to send arbitrary stuff to servers by default
[ "$TERM" = "xterm-kitty" ] && alias ssh="TERM=xterm-256color ssh"

# Utility colours
alias ls="ls --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# macOS coreutils shenans
if [ ! -z "$NT_IS_MACOS" ]; then
	command -v gls >/dev/null \
		&& alias ls="gls --color=always --group-directories-first" \
		|| alias ls="ls -G"
	command -v gawk >/dev/null && alias awk="gawk"
	command -v gsed >/dev/null && alias sed="gsed"
	command -v gpaste >/dev/null && alias paste="gpaste"
	command -v ggrep >/dev/null && alias grep="ggrep"
	command -v grm >/dev/null && alias rm="grm"
fi

# dotfiles management
alias d="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME"


# Shortcuts
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"
alias vv="NT_NVIM_IDE=1 nvim"

alias g="git"

alias srcb="source $HOME/.bashrc"
alias srcz="source $HOME/.zshrc"
alias srcp="source $HOME/.profile"
alias srca="source $HOME/.config/aliasrc"
alias srca="source $HOME/.config/shortcutrc"

alias e="$FILE"
alias r="ranger"

alias mem="ps axch -o cmd:15,%mem --sort=-%mem | sed 10q"
alias cpu="ps axch -o cmd:15,%cpu --sort=-%cpu | sed 10q"
alias qr="qrencode -t ansiutf8"
alias tn1="tail -n+1 -v"

alias drag="dragon-drop -x"
alias rcp="rsync -vzrh --times --stats --progress --itemize-changes"
alias ccat="highlight --out-format=ansi"
alias kif="kinit -f"

if [ -z "$WAYLAND_DISPLAY" ]; then
	alias pbcopy="xclip -selection clipboard"
else
	alias pbcopy="wl-copy"
fi
alias pbc="pbcopy"

# Folder quick-jump-into-a-1depth-subdir tech
folder_fzf_cd() {
	basedir="$1"
	shift
	[ -z "$1" ] && cd "$basedir" && return  # nothing = instant jump to basedir
	[ "$1" = "-" ] && 1=""  # provide '-' to not instant jump
	local x="$(cd "$basedir" && fd . --exact-depth 1 --type d --path-separator '' | fzf -0 -1 -e -q "$*" --preview "ls --color=always {}")"
	[ ! -z "$x" ] && cd "$basedir/$x" || echo "[WARN] Not found"
}

# ranger_cd
[ -f "$HOME/.config/ranger/shell_automatic_cd.sh" ] && . "$HOME/.config/ranger/shell_automatic_cd.sh" && alias ranger="ranger_cd"

# yt-dlp nice defaults
alias ytaudio='yt-dlp --extractor-args "youtube:player_client=default,ios" -x --audio-format mp3 --embed-thumbnail --embed-metadata'
alias ytd='yt-dlp --extractor-args "youtube:player_client=default,ios" --embed-chapters --embed-subs --sponsorblock-mark default --sub-lang "en.*,ja.*,ko.*,zh.*" --sub-format="ass/srt/best" --merge-output-format mkv'


# Fedora
# Package manager (dnf)
alias di="sudo dnf install"
alias dr="sudo dnf remove"
alias dU="sudo dnf upgrade"
alias ds="dnf search"
alias rQ="rpm -qa"


# Misc laptop
# Wireless force rescan for APs
alias wscan="nmcli device wifi rescan"
alias wreset="sudo sh -c 'rmmod iwldvm && sudo modprobe iwldvm'"

# macOS shortcuts
if [ ! -z "$NT_IS_MACOS" ]; then
	alias flushdns="dscacheutil -flushcache; sudo killall -HUP mDNSResponder"

	# Packages
	alias bI="brew install"
	alias bIc="brew install --cask"
	alias bR="brew uninstall"
	alias bU="brew upgrade"
	alias bQ="brew list"
	alias bQc="brew list --cask"
fi

# Utility functions
# Template copier thing - Copy a template and edit it.
templateEdit() {
	[ ! -f "$2" ] && cp "$HOME/template/$1" "$2"
	$EDITOR "$2"
}
alias txa="templateEdit assignment.tex"
alias txt="templateEdit tutorial.tex"
alias txT="templateEdit tutorial.md"
alias txg="templateEdit general.tex"

# Fuzzy find file -> vim
vf() { fzf | xargs -r -I % $EDITOR % ;}
# vf for scripts dir (subshell so no cd switch)
vfs() { ( cd $HOME/.scripts && vf ) ;}

# nohup/disown no output combo opener
nh() {
	nohup "$@" >/dev/null 2>&1 &
	disown
}
# Open with xdg-open handler in background
alias open="nh xdg-open"
alias reveal="nh dolphin --select --new-window"

# timestamps with any decimal points/guessed precision (ns/ms/etc)
ts() {
	[ -z "$1" ] && { gdate +%s%N | sed 's/./&./10'; return; }
	gdate -d "@$(echo "$1" | sed '/^[0-9]\{10\}\([0-9]\{3\}\)\{1,3\}$/ s/./&./10')"
}

# Timezone helpers with things i usually interact with
alias tjp="TZ=Asia/Tokyo "
alias tkr="TZ=Asia/Seoul "
alias thk="TZ=Asia/Hong_Kong "
alias tchi="TZ=America/Chicago "
alias tutc="TZ=UTC "

# 'pipelining' utils e.g. `docker ps -a | skip 1 | col 1 |:: docker rm _`
# from: https://news.ycombinator.com/item?id=38769352
alias ::='sed "$ s/\n$//" | xargs -I_ --'
col() { eval "awk '{ print \$$1 }'" ;}
skip() { tail -n +$(($1 + 1)) ;}
take() { head -n $1 ;}
# my own scuffed takes lol
dcol() { eval "awk -F$2 '{ print \$$1 }'" ;}
replace() { tr "$1" "$2" | sed "s/$2\$//" ;}
commas() { replace "\n" "," ;}
piped() { replace "\n" "|" ;}
appendl() { sed "s&\$&$1&" ;}
prependl() { sed "s&^&$1&" ;}
listify() { sed 's/^/ - /' ;}
# not the best implementation, but quick hack for lines of things -> sql IN
tuples() { sed "s/$/',/;s/^/'/" | sed -z 's/\n/ /g;s/^/(/;s/, $/)\n/' ;}
path1() { dcol 1 '/' ;}
prepend() { cat <(echo "$1") - ;}

# Show JSON if interactive, or Pipe through
showjson() { [ -t 1 ] && { jq -C | less -R ;} || cat ;}

# curl silently, but also display the url while at it (intended for easy get only)
curllog() {
	echo "[DEBUG] $1" >&2
	curl -s "$1"
}

[ -f "$HOME/.config/shortcutrc" ] && . "$HOME/.config/shortcutrc"
# Host-based include
[ -f "$NT_OVERRIDES/aliasrc" ] && . "$NT_OVERRIDES/aliasrc" 2>/dev/null
