#!/bin/sh

# Nick's aliases for shells
# Here we go...

# General shell
alias t="$TERMINAL"
alias q="exit"
alias cl="clear"

# Some neat general util stuff
alias cp='cp -iv'
alias mv='mv -iv'
alias ls='ls --color=auto --group-directories-first'
alias lss='ls -shN'
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias ssh='TERM=xterm-256color ssh'

# dotfiles management
alias d="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME"

# Shortcuts for program + option
# General
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias e="$FILE"
alias r="ranger"
alias l="lf"
alias g="git"
alias o="xdg-open"
alias open="setsid xdg-open"
alias psg="ps aux | grep"
alias mem="ps axch -o cmd:15,%mem --sort=-%mem | sed 10q"
alias cpu="ps axch -o cmd:15,%cpu --sort=-%cpu | sed 10q"
alias sdn="shutdown now"
alias reb="reboot"
alias mkp="mkdir -p"
alias sudo="sudo "
alias sudoo="sudo -E "
alias drag="dragon-drop -x"
alias rcp="rsync -vzrh --times --stats --progress --itemize-changes"
alias usbgl="sudo usbguard list-devices -b"
alias usbga="sudo usbguard allow-device"
if [ -z "$WAYLAND_DISPLAY" ]; then
	alias pbcopy="xclip -selection clipboard"
else
	alias pbcopy="wl-copy"
fi

jg() {
	jumptool generate && echo "Generated new jump aliases."
	. $HOME/.config/shortcutrc && echo "Reloaded shell shortcut aliases."
	ps -p $$ 2>/dev/null | grep -q zsh && source $HOME/.config/zshnameddirs && echo "Reloaded zsh named dirs."
}

# lf with cd
[ -f "$HOME/.config/lf/lfcd" ] && . "$HOME/.config/lf/lfcd" && alias lf="lfcd"
# ranger_cd
[ -f "$HOME/.config/ranger/shell_automatic_cd.sh" ] && . "$HOME/.config/ranger/shell_automatic_cd.sh" && alias ranger="ranger_cd"

# Fedora
# Package manager (dnf)
alias di="sudo dnf install"
alias dr="sudo dnf remove"
alias dU="sudo dnf upgrade"
alias ds="dnf search"
alias rQ="rpm -qa"

# Arch
# Package manager (pacman)
alias p="sudo pacman"
alias pS="sudo pacman -S"
alias pR="sudo pacman -R"
alias pU="sudo pacman -Syu"
alias pQ="pacman -Q"
# yay (AUR)
alias y="yay"
alias yS="yay -S"
alias yR="yay -R"
alias yU="yay -Syu"

# Service management
alias s="systemctl"
#alias ss="sudo systemctl"
alias sst="systemctl status"
alias ssr="sudo systemctl restart"
alias sus="systemctl --user status"
alias sur="systemctl --user restart"

# (La)TeX
alias tli="sudo tlmgr install"
alias ltp="latexmk -pdf"
alias ltc="latexmk -c"


# Misc
# Wireless force rescan for APs
alias wscan="nmcli device wifi rescan"
alias wreset="sudo sh -c 'rmmod iwldvm && sudo modprobe iwldvm'"

# OpenMPI (Uni FIT3143)
# This loads the dev environment, ready to use commands including 'mpirun'
# Fedora: `dnf install openmpi openmpi-devel libomp libomp-devel`
alias mpiload="module load mpi/openmpi-x86_64"


# Template copier thing
# Copy a template and edit it.
templateEdit() {
	[ ! -f "$2" ] && cp "$HOME/template/$1" "$2"
	$EDITOR "$2"
}
alias txa="templateEdit assignment.tex"
alias txt="templateEdit tutorial.tex"
alias txT="templateEdit tutorial.md"
alias txg="templateEdit general.tex"

# Fuzzy find file -> vim
vf() { fzf | xargs -r -I % $EDITOR % ;}
# vf for scripts dir (subshell so no cd switch)
vfs() { ( cd $HOME/.scripts && vf ) ;}
# jumptool listings
cdj() { d="$(jumptool dir fzf)" && cd "$d" ;}
vfc() { jumptool config fzf ;}


# Host-based include
[ -f "$NT_OVERRIDES/aliasrc" ] && . "$NT_OVERRIDES/aliasrc"
[ -f "$HOME/.config/shortcutrc" ] && . "$HOME/.config/shortcutrc"


# wal colors
[ ! -z "$NT_USE_WAL" ] && [ -r "$HOME/.cache/wal/sequences" ] && (cat $HOME/.cache/wal/sequences &)

# tmux ssh rename
# if [ "$TERM" = "tmux-256color" ] && [ -n "$TMUX" ]; then
# 	ssh() {
# 		tmux rename-window "ssh($(echo $* | cut -d . -f 1))"
# 		command ssh "$@"
# 		tmux set-window-option automatic-rename "on" 1>/dev/null
# 	}
# fi
