#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config focus_follows_pointer true

# wal
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# rules
# floater
bspc rule -a 'St:floater' state=floating rectangle=850x500+0+0 center=true

xsetroot -cursor_name left_ptr &
pgrep -f desknamer || desknamer 1>/dev/null &
pgrep bspswallow || bspswallow 1>/dev/null &
