#!/bin/sh

bspc monitor -d 一 二 三 四 五 六 七 八 九
#bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config focus_follows_pointer true

# wal
$HOME/.config/wal/applybspwm

# rules
# floater
bspc rule -a 'St:floater' state=floating rectangle=850x500+0+0 center=true
bspc rule -a 'KeePassXC' state=floating rectangle=900x550+0+0 center=true

# cursor to left
xsetroot -cursor_name left_ptr &

# run desknamer - restart it as weird looping if not
pkill -f desknamer; desknamer 1>/dev/null &

# swallowing
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -fl 'pidswallow -gl' || pidswallow -gl
