#!/bin/sh

[ ! -f $HOME/.cache/wal/colors.sh ] && exit
. "$HOME/.cache/wal/colors.sh"
bspc config normal_border_color "$color8"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
