#!/bin/sh

[ ! -f $HOME/.cache/wal/colors.sh ] && exit
. "$HOME/.cache/wal/colors.sh"
echo $color1
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
