#!/bin/sh

mkdir -p $HOME/.config/dunst
ln -sf $HOME/.cache/wal/dunstrc $HOME/.config/dunst/dunstrc
pkill dunst; dunst &

pidof dwm >/dev/null && xdotool key super+F5
pidof bspwm >/dev/null && bspc wm -r
