#!/bin/sh

# mainly used in ranger for interactive confirm empty

echo "Trash list:"
trash-list

echo ""
read -p "Really empty trash? [y/n] " yn
case $yn in
	[Yy]*) trash-empty && echo "Trash emptied."
esac
